# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [27]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [28]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', delimiter="\t")

### Step 4. How many products cost more than $10.00?

In [29]:
#change the price column into a float
chipo['item_price'] = chipo['item_price'].map(lambda x: x[1:]).astype(float)

In [30]:
# change the price column into a per-item price (the data comes in as price for all quantities ordered)
chipo['item_price'] = round((chipo['item_price'] / chipo['quantity']), 2)
chipo.sort_values('item_price').head(20)
#ten = chipo.loc[chipo['item_price'] > 10.00]
#len(ten['item_name'].unique())
#ten['item_name'].value_counts()

      order_id  quantity      item_name choice_description  item_price
3364      1349         2    Canned Soda        [Coca Cola]        1.09
818        338         3  Bottled Water                NaN        1.09
1182       485         2  Bottled Water                NaN        1.09
162         73         2    Canned Soda        [Diet Coke]        1.09
821        338         1    Canned Soda        [Coca Cola]        1.09
2235       901         4    Canned Soda           [Sprite]        1.09
2754      1093         1  Bottled Water                NaN        1.09
171         76         2    Canned Soda  [Diet Dr. Pepper]        1.09
1057       435         1    Canned Soda     [Mountain Dew]        1.09
2768      1098         1    Canned Soda           [Sprite]        1.09
3498      1405         1    Canned Soda  [Diet Dr. Pepper]        1.09
179         81         1    Canned Soda        [Coca Cola]        1.09
2774      1101         1    Canned Soda           [Sprite]        1.09
2206       889         1    Canned Soda     [Mountain Dew]        1.09
1177       484         2  Bottled Water                NaN        1.09
3740      1494         1    Canned Soda           [Sprite]        1.09
3062      1220         1    Canned Soda       [Dr. Pepper]        1.09
195         87         1    Canned Soda        [Coca Cola]        1.09
4069      1629         1  Bottled Water                NaN        1.09
378        164         1    Canned Soda     [Mountain Dew]        1.09

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [31]:
chipo.loc[:,('item_name', 'item_price')]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [32]:
chipo.sort_values('item_name')

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [46]:
chipo.sort_values(['item_price', 'quantity'], ascending = False).head(1)

,order_id,quantity,item_name,choice_description,item_price
281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",11.89

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [22]:
chipo.loc[chipo['item_name'] == 'Veggie Salad Bowl'].sum()['quantity']

18

### Step 9. How many times did someone order more than one Canned Soda?

In [47]:
sodas = chipo[(chipo['item_name'].str.contains('Canned')) & (chipo['quantity'] > 1)]
sodas

      order_id  quantity          item_name choice_description  item_price
18           9         2        Canned Soda           [Sprite]        1.09
51          23         2        Canned Soda     [Mountain Dew]        1.09
162         73         2        Canned Soda        [Diet Coke]        1.09
171         76         2        Canned Soda  [Diet Dr. Pepper]        1.09
350        150         2        Canned Soda        [Diet Coke]        1.09
352        151         2        Canned Soda        [Coca Cola]        1.09
492        206         2  Canned Soft Drink        [Diet Coke]        1.25
651        270         2  Canned Soft Drink             [Coke]        1.25
689        284         3  Canned Soft Drink        [Diet Coke]        1.25
698        287         2        Canned Soda        [Coca Cola]        1.09
700        288         2        Canned Soda        [Coca Cola]        1.09
791        325         2  Canned Soft Drink             [Coke]        1.25
850        350         3  Canned Soft Drink           [Sprite]        1.25
909        376         2        Canned Soda     [Mountain Dew]        1.09
917        379         3  Canned Soft Drink         [Lemonade]        1.25
1091       450         2        Canned Soda       [Dr. Pepper]        1.09
1092       450         2        Canned Soda        [Coca Cola]        1.09
1338       546         2  Canned Soft Drink             [Coke]        1.25
1373       560         2  Canned Soft Drink             [Coke]        1.25
1377       561         2  Canned Soft Drink         [Lemonade]        1.25
1412       574         2  Canned Soft Drink        [Diet Coke]        1.25
1559       633         3  Canned Soft Drink             [Coke]        1.25
1760       710         2  Canned Soft Drink        [Diet Coke]        1.25
1878       759         2  Canned Soft Drink             [Coke]        1.25
1879       759         2  Canned Soft Drink        [Diet Coke]        1.25
1944       787         2        Canned Soda       [Dr. Pepper]        1.09
2135       859         2        Canned Soda        [Diet Coke]        1.09
2235       901         4        Canned Soda           [Sprite]        1.09
2274       915         2  Canned Soft Drink             [Coke]        1.25
2513       999         2  Canned Soft Drink           [Sprite]        1.25
2766      1097         2  Canned Soft Drink        [Diet Coke]        1.25
2905      1156         2        Canned Soda        [Coca Cola]        1.09
2906      1156         2        Canned Soda           [Sprite]        1.09
2995      1191         2  Canned Soft Drink           [Sprite]        1.25
3018      1200         2  Canned Soft Drink        [Diet Coke]        1.25
3089      1231         3  Canned Soft Drink        [Diet Coke]        1.25
3128      1247         3  Canned Soft Drink        [Diet Coke]        1.25
3135      1250         2  Canned Soft Drink             [Coke]        1.25
3152      1258         2        Canned Soda       [Dr. Pepper]        1.09
3159      1261         2  Canned Soft Drink        [Diet Coke]        1.25
3242      1298         2  Canned Soft Drink        [Diet Coke]        1.25
3364      1349         2        Canned Soda        [Coca Cola]        1.09
3418      1371         2  Canned Soft Drink        [Diet Coke]        1.25
3524      1417         2  Canned Soft Drink             [Coke]        1.25
3592      1440         2        Canned Soda        [Diet Coke]        1.09
3609      1446         2  Canned Soft Drink        [Diet Coke]        1.25
3699      1482         2  Canned Soft Drink        [Diet Coke]        1.25
3866      1550         2        Canned Soda     [Mountain Dew]        1.09
3880      1556         2  Canned Soft Drink             [Coke]        1.25
3973      1592         4  Canned Soft Drink             [Coke]        1.25
4016      1608         2  Canned Soft Drink        [Diet Coke]        1.25
4027      1611         2  Canned Soft Drink             [Coke]        1.25
4098      1642         3  Canned Soft Drink        [Diet Coke]        1.25
4490      1786         4  Canned Soft Drink             [Coke]        1.25
4491      1786         4  Canned Soft Drink           [Sprite]        1.25
4499      1789         2  Canned Soft Drink             [Coke]        1.25
4560      1812         2  Canned Soft Drink             [Coke]        1.25